### ISSUE TITLE
NGettext: Translation file loading fail: Can not find MO file name in locale directory "Locale".

### ISSUE THREAD

**Issue by D-Bullock** [robert-j-engdahl/ngettext-wpf#14]
Hi,

Sorry for the vague title. I'm trying to debug why I can't get translations appearing. I've got the same folder structure as the demo - Locale\da-DK\LC_MESSAGES\<appName>.po  and Locale\da-DK\LC_MESSAGES\<appName>.mo

My application is rather trivial, just a main.xaml with a bunch of functions attached.

I've been getting the unhelpful error message NGettext: Translation file loading fail: Can not find MO file name in locale directory "Locale". Not sure what I should be doing next to resolve the issue. 

I know I've not provided much info but I'm not sure what you need.

**Comment by robert-j-engdahl** [comment]
I really wan't to help you out here.  Is there any way I can see your code and figure out whats wrong?

**Comment by robert-j-engdahl** [comment]
Did you make sure these files were copied to the bin directory?  Also, if you keep your .mo files in a library project and you publish with clickonce you need to include the .mo files as links in the clickonce project.

**Comment by D-Bullock** [comment]
Congrats! On almost no info you found the root cause :)

The issue was that I hadn't marked the files to be copied to the debug folder. I incorrectly assumed that the library would be doing some kind of bundling, which doesn't make a lot of sense now I say it.

Perhaps the readme guide should mention it.

**Comment by robert-j-engdahl** [comment]
Pull requests are welcome.  But I am adding it right away.
