### ISSUE TITLE
Translating text with single quotes in it

### ISSUE THREAD

**Issue by D-Bullock** [robert-j-engdahl/ngettext-wpf#16]
Hi, 

What is the correct way to format this "{wpf:Gettext it's}"? I'm unsure how to format it so that both the xaml error checker and the UpdateTranslations.ps1 script are happy

**Comment by robert-j-engdahl** [comment]
A fix is coming up shortly.

**Comment by robert-j-engdahl** [comment]
The correct way is `{wpf:Gettext it\'s}` and a few seconds ago I implemented support for that.
