### ISSUE TITLE
Support {wpf:gettext 'string'}

### ISSUE THREAD

**Issue by D-Bullock** [robert-j-engdahl/ngettext-wpf#18]
The issue is entirely in the extraction process. Currently, when extracted using `XGetText-Xaml`, it will enter the line 
```
msgid "'string'"
```

whereas it should enter the line
```
msgid "string"
```

**Comment by robert-j-engdahl** [comment]
Well spotted.

https://msdn.microsoft.com/en-us/library/ee200269.aspx it is supported {MarkupExtension 'quoted string value'} is allowed syntax and the quoted string value without the quotes is passed on as the arguments to the `MarkupExtension`.
