### ISSUE TITLE
Issue loading locale files

### ISSUE THREAD

**Issue by D-Bullock** [robert-j-engdahl/ngettext-wpf#25]
We run a bootloader to startup our application, which is breaking the location finding logic. 
(ie, startup.exe will run actualProgram.exe)

Is there any inbuilt way to define where the locale files are stored? I've not been able to spot it

**Comment by robert-j-engdahl** [comment]
Actually I chose not to do that in an attempt to enforce some convention (as I wasted quite some time myself figuring out which directory was the right one when first starting to use ngettext).  

Each running process in Windows has a notion of current working directory, and the .mo files are assumed to be located relative to that.   Your startup.exe can be made to start your actualProgram.exe from the right directory.  See for instance https://stackoverflow.com/q/47247192/2154774
