### ISSUE TITLE
Gettext in StringFormat

### ISSUE THREAD

**Issue by Jogge** [robert-j-engdahl/ngettext-wpf#30]
I would like to use Gettext in StringFormat of a Binding like this:

`<TextBlock Text="{Binding Name, StringFormat={wpf:Gettext Name: {0}}}">`

**Comment by D-Bullock** [comment]
Unfortunately that's a limitation of wpf's xaml. You can look at writing a multibinding wrapper to allow binding to occur (see https://www.codeproject.com/Articles/456589/Bindable-Converter-Parameter for an example)

**Comment by robert-j-engdahl** [comment]
@D-Bullock is absolutely right.  But this is a frustrating limitation of XAML.

However, while we cannot change the BindingExtension of WPF to support this, we might be able to do this the other way around.

It might be possible to do something like

```
<TextBlock Text="{wpf:Gettext Name: {0}, Param0={Binding Name}}"/>
```

or

```
<TextBlock Text="{wpf:Gettext Name: {0}, Param0Path=Name}"/>
```

Both the XGetText.Xaml.ps1 and GettextExtension would need to be updated.

**Comment by robert-j-engdahl** [comment]
This will be done with the GettextStringFormatConverter XAML extension, which is applied to the Converter property of the Binding.
