### ISSUE TITLE
GNOME glib syntax does not work for static translation methods in C#

### ISSUE THREAD

**Issue by Jogge** [robert-j-engdahl/ngettext-wpf#31]
`_("Context|Message")` should show up as `Message` as source text and `Context` as context, but it shows up as `Context|Message` as source text and no context.

Related to https://github.com/robert-j-engdahl/ngettext-wpf/issues/22

**Comment by robert-j-engdahl** [comment]
xgettext supports this (kind-a) out of the box, just use the option `-k_:0g` when invoking xgettext.  (It will give anoying warnings when you forget to specify a context)

However, as you point out the static translation methods in this library doesn't detect the `|` as a context separator.  And it would be awesome if it did.

**Comment by robert-j-engdahl** [comment]
Is fixed in next release
