### ISSUE TITLE
Does not support , (comma) in source text

### ISSUE THREAD

**Issue by PGPoulsen** [robert-j-engdahl/ngettext-wpf#33]
Image below show the error :)

![2019-02-23_20h57_02](https://user-images.githubusercontent.com/38398596/53291572-a5b19e00-37b5-11e9-8d6b-5243620ea29e.png)

A way to deal with it is to surround the string with quotes ```{wpf:Gettext 'What creates the hazard e.g. people, materials, method or environment?'}```, but I'm not sure if that is the intended fix.

Yours
/peter

**Comment by robert-j-engdahl** [comment]
A fix will be included in next release.
